### ISSUE TITLE
Runtime error with ngen multi_bmi_lasam_sft_smp

### ISSUE THREAD

**Issue by madMatchstick** [NOAA-OWP/LGAR-C#3]
```
lasam % ../cmake_build/ngen data/catchment_data.geojson cat-27 data/nexus_data.geojson nex-26 extern/LGAR-C/configs/realization_config_lasam_sft.json
```
After initialization, seeing the following error at runtime, 
```
libc++abi: terminating with uncaught exception of type realization::ConfigurationException: Multi BMI formulation cannot be created from config: cannot find available data provider to satisfy set of deferred provisions for nested module at index 1: {Qb_topmodel}
zsh: abort      ../cmake_build/ngen data/catchment_data.geojson cat-27 data/nexus_data.geojso
```

@ajkhattak - can you confirm that the `multi_bmi_lasam_sft_smp` realization is correct?  Specifically the `sloth` section [here](https://github.com/NOAA-OWP/LGAR-C/blob/6b133d06541318cc634aa6931fc0fdfb2bc8d722/configs/realization_config_lasam_sft.json#L29)? Thanks!

**Comment by ajkhattak** [comment]
oh yeah, I think this file is outdated due to some recent changes in SoilMoistureProfiles. We will update it when testing LASAM coupling with SFT.

**Comment by ajkhattak** [comment]
@madMatchstick this has been fixed. Can you please re-run it to check it works for you this time?
